---
#config_file
appName: sp1
clientId: 6fJ46TOQYv0eENfe1O0mikgW8gsa
clientSecret: glO9_tqgXIjdYN0okp9oCCydRega
storeConnectorType: JDBC
database: ArtifactStore5
dbUserName: root
flowMode: poll
clientNotificationEndpoint: http://localhost/Sp2/clientNotificationEnd
dbUserPassword: susa
