---
#config_file
appName: sp1
clientId: 6fJ46TOQYv0eENfe1O0mikgW8gsa
clientSecret: f1vHL7KONcFkjpadujRT8IcAlwga
storeConnectorType: JDBC
database: ArtifactStore2
dbUserName: root
flowMode: poll
clientNotificationEndpoint: http://localhost/Sp2/clientNotificationEnd
dbUserPassword: susa
